# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyTUID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_13', models.CharField(max_length=13, unique=True, verbose_name='ISBN-13')),
                ('title', models.CharField(max_length=42, verbose_name='title')),
                ('state', models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('PP', 'Proposed'), ('OL', 'Obsolete')], default='AC', max_length=2, verbose_name='status')),
                ('author', models.CharField(max_length=64, verbose_name='author')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price')),
                ('publisher', models.CharField(max_length=64, verbose_name='publisher')),
                ('year', models.IntegerField(verbose_name='year')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OD', 'Ordered'), ('RJ', 'Rejected'), ('AR', 'Arrived')], default='PD', max_length=2, verbose_name='status')),
                ('hint', models.TextField(blank=True, verbose_name='hint')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyBuchaktion.Book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderTimeframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('allowed_orders', models.IntegerField(default=0, verbose_name='allowed orders')),
                ('spendings', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='spendings')),
            ],
            options={
                'verbose_name': 'order timeframe',
                'verbose_name_plural': 'order timeframes',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('W', 'Winter term'), ('S', 'Summer term')], default='W', max_length=1, verbose_name='season')),
                ('year', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='year')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='budget')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_id', models.CharField(blank=True, default='', max_length=12, null=True, unique=True, verbose_name='library id')),
                ('tuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyTUID.TUIDUser', verbose_name='TUID User')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='TucanModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=13, unique=True, verbose_name='module id')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('last_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.Semester', verbose_name='last offered')),
                ('literature', models.ManyToManyField(to='pyBuchaktion.Book', verbose_name='literature')),
            ],
            options={
                'verbose_name': 'TUCaN module',
                'verbose_name_plural': 'TUCaN modules',
            },
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('season', 'year')]),
        ),
        migrations.AddField(
            model_name='ordertimeframe',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.Semester', verbose_name='semester'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.OrderTimeframe', verbose_name='order timeframe'),
        ),
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyBuchaktion.Student', verbose_name='student'),
        ),
    ]
