# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_13', models.CharField(max_length=13, unique=True)),
                ('title', models.CharField(max_length=42)),
                ('state', models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('PP', 'Proposed'), ('OL', 'Obsolete')], default='AC', max_length=2)),
                ('author', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OD', 'Ordered'), ('RJ', 'Rejected'), ('AR', 'Arrived')], default='PD', max_length=2)),
                ('hint', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyBuchaktion.Book')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTimeframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('spendings', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('W', 'Wintersemester'), ('S', 'Sommersemester')], default='W', max_length=1)),
                ('year', models.DecimalField(decimal_places=0, max_digits=2)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TucanModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('last_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.Semester')),
                ('literature', models.ManyToManyField(to='pyBuchaktion.Book')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('season', 'year')]),
        ),
        migrations.AddField(
            model_name='ordertimeframe',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.Semester'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.OrderTimeframe'),
        ),
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyBuchaktion.Student'),
        ),
    ]
