# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=140, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=140, verbose_name='title'),
        ),
    ]
