# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-04 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='ordertimeframe',
            options={'verbose_name': 'order timeframe', 'verbose_name_plural': 'order timeframes'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'semester', 'verbose_name_plural': 'semesters'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='tucanmodule',
            options={'verbose_name': 'TUCaN module', 'verbose_name_plural': 'TUCaN modules'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=64, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(max_length=13, unique=True, verbose_name='ISBN-13'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RJ', 'Rejected'), ('PP', 'Proposed'), ('OL', 'Obsolete')], default='AC', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=42, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyBuchaktion.Book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hint',
            field=models.TextField(verbose_name='hint'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timeframe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.OrderTimeframe', verbose_name='order timeframe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('OD', 'Ordered'), ('RJ', 'Rejected'), ('AR', 'Arrived')], default='PD', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyBuchaktion.Student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='ordertimeframe',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='ordertimeframe',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.Semester', verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='ordertimeframe',
            name='spendings',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='spendings'),
        ),
        migrations.AlterField(
            model_name='ordertimeframe',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.CharField(choices=[('W', 'Winter term'), ('S', 'Summer term')], default='W', max_length=1, verbose_name='season'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='tucanmodule',
            name='last_offered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyBuchaktion.Semester', verbose_name='last offered'),
        ),
        migrations.AlterField(
            model_name='tucanmodule',
            name='literature',
            field=models.ManyToManyField(to='pyBuchaktion.Book', verbose_name='literature'),
        ),
        migrations.AlterField(
            model_name='tucanmodule',
            name='module_id',
            field=models.CharField(max_length=13, unique=True, verbose_name='module id'),
        ),
        migrations.AlterField(
            model_name='tucanmodule',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
