# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0002_auto_20170504_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, verbose_name='hint'),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Nicht gesetzt'), ('de', 'German'), ('en', 'English')], default='', max_length=2, verbose_name='preferred language'),
        ),
    ]
