# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0002_auto_20170404_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='The Publisher', max_length=64, verbose_name='publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1337, verbose_name='year'),
            preserve_default=False,
        ),
    ]
