# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0003_auto_20170404_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='library_id',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='library id'),
        ),
    ]
