# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0003_auto_20170516_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Not selected'), ('de', 'German'), ('en', 'English')], default='', max_length=2, verbose_name='preferred language'),
        ),
    ]
