# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 14:00
from __future__ import unicode_literals

from django.db import migrations

def move_email(apps, schema_editor):
    Student = apps.get_model("pyBuchaktion", "Student")
    TUIDUser = apps.get_model("pyTUID", "TUIDUser")

    for student in Student.objects.all():
        if student.tuid_user.email is not None:
            student.email = student.tuid_user.email
            student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0004_auto_20170518_1551'),
    ]

    operations = [
        migrations.RunPython(move_email)
    ]
