# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0004_student_library_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hint',
            field=models.TextField(blank=True, verbose_name='hint'),
        ),
        migrations.AlterField(
            model_name='student',
            name='library_id',
            field=models.CharField(blank=True, default='', max_length=12, null=True, unique=True, verbose_name='library id'),
        ),
    ]
