# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyTUID', '0001_initial'),
        ('pyBuchaktion', '0005_auto_20170405_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tuid_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pyTUID.TUIDUser', verbose_name='TUID User'),
            preserve_default=False,
        ),
    ]
