# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0005_auto_20170518_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tuid_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyTUID.TUIDUser', verbose_name='TUID User'),
        ),
    ]
