# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0006_student_tuid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimeframe',
            name='allowed_orders',
            field=models.IntegerField(default=0, verbose_name='allowed orders'),
        ),
    ]
