# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0006_auto_20170523_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True, verbose_name='key')),
                ('text_de', models.TextField(max_length=4000, verbose_name='german text')),
                ('text_en', models.TextField(max_length=4000, verbose_name='english text')),
            ],
            options={
                'verbose_name_plural': 'display messages',
                'verbose_name': 'display message',
            },
        ),
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=128, verbose_name='german name')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='english name')),
            ],
            options={
                'verbose_name_plural': 'module categories',
                'verbose_name': 'module category',
            },
        ),
        migrations.RenameModel(
            old_name='TucanModule',
            new_name='Module',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
    ]
