# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0007_auto_20170529_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyBuchaktion.ModuleCategory', verbose_name='category'),
        ),
    ]
