# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0008_module_category'),
    ]

    operations = [
        migrations.RenameField('Module', 'name', 'name_de'),
        migrations.AddField(
            model_name='module',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name_de',
            field=models.CharField(max_length=128, verbose_name='german name'),
        ),
    ]
