# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0010_auto_20170605_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='literature',
            field=models.ManyToManyField(through='pyBuchaktion.Literature', to='pyBuchaktion.Book', verbose_name='literature'),
        ),
        migrations.AlterField(
            model_name='module',
            name='literature_save',
            field=models.ManyToManyField(related_name='modules_save', to='pyBuchaktion.Book', verbose_name='literature'),
        ),
    ]
