# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 21:29
from __future__ import unicode_literals

from django.db import migrations

def move_literature(apps, schema_editor):
    Module = apps.get_model("pyBuchaktion", "Module")
    Literature = apps.get_model("pyBuchaktion", "Literature")

    for module in Module.objects.all():
        for book in module.literature_save.all():
            m2 = Literature(module=module, book=book)
            m2.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0011_auto_20170605_2328'),
    ]

    operations = [
        migrations.RunPython(move_literature)
    ]
