# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0013_remove_module_literature_save'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literature',
            options={'verbose_name': 'literature', 'verbose_name_plural': 'literature'},
        ),
        migrations.AddField(
            model_name='literature',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='literature',
            name='in_tucan',
            field=models.BooleanField(default=True, verbose_name='in TUCaN'),
        ),
        migrations.AlterUniqueTogether(
            name='literature',
            unique_together=set([('book', 'module')]),
        ),
    ]
