# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyBuchaktion', '0014_auto_20170606_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecategory',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_info', to='pyBuchaktion.Book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_info', to='pyBuchaktion.Module', verbose_name='module'),
        ),
    ]
